

target 'LangApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  platform :ios, '13.0'

  # Pods for LangApp

  target 'LangAppTests' do
	pod 'ReSwift'
  end

  target 'LangAppUITests' do
    # Pods for testing
  end

end
